"""Add fields for additional photos and videos to Post model

Revision ID: 5fa8358caa59
Revises: 
Create Date: 2024-08-31 15:45:36.136353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa8358caa59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_photo_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_photo_urls', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('main_video_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_video_urls', sa.String(length=300), nullable=True))
        batch_op.drop_column('video_url')
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('additional_video_urls')
        batch_op.drop_column('main_video_url')
        batch_op.drop_column('additional_photo_urls')
        batch_op.drop_column('main_photo_url')

    # ### end Alembic commands ###
