"""Update models

Revision ID: 9b0863daba24
Revises: db707dd257af
Create Date: 2024-09-04 00:43:54.267740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0863daba24'
down_revision = 'db707dd257af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_index('ix_user_telegram')
        batch_op.create_index(batch_op.f('ix_user_telegram'), ['telegram'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram'))
        batch_op.create_index('ix_user_telegram', ['telegram'], unique=1)
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
